### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

### ISSUE THREAD

**Issue by cuongtl1992** [mcollina/mqemitter-redis#22] opened 2020-03-18 05:05 UTC
I created MQTT broker with eadesjs with backend is redis using mqemitter-redis but it has an issue
when i connect and test with [MQTT explorer](http://mqtt-explorer.com/) then it crash loop and throw this exception:

at Socket.emit (events.js:198:13)
4|kv-mqtt- | AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
4|kv-mqtt- | 
4|kv-mqtt- |   assert(message)
4|kv-mqtt- | 
4|kv-mqtt- |     at MQEmitterRedis.emit (/app/node_modules/mqemitter-redis/node_modules/mqemitter/mqemitter.js:87:3)
4|kv-mqtt- |     at handler (/app/node_modules/mqemitter-redis/mqemitter-redis.js:48:12)
4|kv-mqtt- |     at Redis.<anonymous> (/app/node_modules/mqemitter-redis/mqemitter-redis.js:58:5)
4|kv-mqtt- |     at Redis.emit (events.js:198:13)
4|kv-mqtt- |     at DataHandler.handleSubscriberReply (/app/node_modules/ioredis/built/DataHandler.js:89:28)
4|kv-mqtt- |     at DataHandler.returnReply (/app/node_modules/ioredis/built/DataHandler.js:47:18)
4|kv-mqtt- |     at JavascriptRedisParser.returnReply (/app/node_modules/ioredis/built/DataHandler.js:21:22)
4|kv-mqtt- |     at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:544:14)
4|kv-mqtt- |     at Socket.DataHandler.redis.stream.on.data (/app/node_modules/ioredis/built/DataHandler.js:25:20)
4|kv-mqtt- |     at Socket.emit (events.js:198:13)

**Comment by mcollina** [comment] 2020-03-18 07:34
Which messages are you sending to cause this? Can you reproduce using http://npm.im/mqtt?

**Comment by cuongtl1992** [comment] 2020-03-18 07:46
@mcollina i using mqttjs for my client but if anyone user use MQTT explorer it will make my broker crash. i debug and finded this issue. When i use mqtt explorer tool in mqemitter will call .emit() function and message is undefined assert(undefined) -> it throw this exception

**Comment by mcollina** [comment] 2020-03-18 08:06
I need a way to reproduce this in a unit test, can you identify what MQTT messages are being sent to cause this?

**Comment by cuongtl1992** [comment] 2020-03-18 08:13
@mcollina i don't have message you can reproduce it by steps :
1. Create MQTT broker with eades and using mqemitter-redis (I run it inside docker container based on image **node:10.16-alpine**)
2. Download tool MQTT Explorer
3. connect and take error.

**Comment by mcollina** [comment] 2020-03-18 08:14
I have no time to fix this, please send a pull request. Thanks.

**Comment by cuongtl1992** [comment] 2020-03-18 08:15
@mcollina okey, thanks u

**Comment by albertxiao** [comment] 2020-10-15 08:03
i'm having same issue, so i have 1 client subscribe to #
and the other client publish to topic with double quotes inside the payload "TEST" <= the double quotes must sent too in the payload
and it's causing same error like this

**Comment by albertxiao** [comment] 2020-10-16 01:00
@cuongtl1992 Is your redis server used for another function than mqtt?

in my case i use it as queue server too, and looks like message from queue server is received by mqttemitter, looks like ioredis not checking if the database index is different, this is dangerous if we have multi purpose redis server.

**Comment by CoDanny** [comment] 2021-04-09 17:22
@albertxiao I don't think this is a problem in ioredis. This is simply who redis work. Note this sentence:
```
Database & Scoping

Pub/Sub has no relation to the key space. It was made to not interfere with it on any level, including database numbers.
Publishing on db 10, will be heard by a subscriber on db 1.
If you need scoping of some kind, prefix the channels with the name of the environment (test, staging, production, ...).
```
from this page: https://redis.io/topics/pubsub

@mcollina What I think it's needed here is the ability to add a namespace to the redis channels for cases where the redis server is also uses for other purposes. This could be an option when creating the emitter.

**Comment by mcollina** [comment] 2021-04-10 21:28
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cuongtl1992** [comment] 2021-04-12 08:10
@albertxiao I created a pull request without unit test. You can check it

**Comment by fmsy** [comment] 2021-11-30 12:16
Duplicate of #47

**Closed** 2021-11-30 13:52 UTC

**Comment by emanuelet** [comment] 2025-03-19 08:49
Just wanted to inform you that we encountered the same error with v6.1.0 that we are testing

```
 
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert(message)
at MQEmitterRedis.emit (/usr/src/app/node_modules/.pnpm/mqemitter@6.0.2/node_modules/mqemitter/mqemitter.js:99:3)
at handler (/usr/src/app/node_modules/.pnpm/mqemitter-redis@6.1.0/node_modules/mqemitter-redis/mqemitter-redis.js:47:12)
at EventEmitter.<anonymous> (/usr/src/app/node_modules/.pnpm/mqemitter-redis@6.1.0/node_modules/mqemitter-redis/mqemitter-redis.js:53:5)
at EventEmitter.emit (node:events:518:28)
at DataHandler.handleSubscriberReply (/usr/src/app/node_modules/.pnpm/ioredis@5.6.0/node_modules/ioredis/built/DataHandler.js:85:28)
at DataHandler.returnReply (/usr/src/app/node_modules/.pnpm/ioredis@5.6.0/node_modules/ioredis/built/DataHandler.js:50:18)
at JavascriptRedisParser.returnReply (/usr/src/app/node_modules/.pnpm/ioredis@5.6.0/node_modules/ioredis/built/DataHandler.js:21:22)
at JavascriptRedisParser.execute (/usr/src/app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:544:14)
at Socket.<anonymous> (/usr/src/app/node_modules/.pnpm/ioredis@5.6.0/node_modules/ioredis/built/DataHandler.js:26:20)
at Socket.emit (node:events:518:28) {
generatedMessage: true,
code: 'ERR_ASSERTION',
actual: undefined,
expected: true,
operator: '=='
}
```
